import Foundation
import AppKit

/// 剪贴板历史：轮询 NSPasteboard changeCount，记录文本、URL、文件与图片。
/// 历史保存在 Application Support；文件条目只保存路径索引，不复制原文件。
/// 容量配置与置顶状态持久化，置顶项不参与条数淘汰。
@MainActor
final class ClipboardHistoryManager: ObservableObject {
    struct Entry: Identifiable, Equatable, Codable {
        enum Kind: String, CaseIterable, Codable {
            case text, url, file, image
        }

        let id: UUID
        let kind: Kind
        let text: String?
        let filePaths: [String]
        let imageData: Data?
        let date: Date
        var isPinned: Bool

        init(id: UUID = UUID(), kind: Kind, text: String? = nil,
             filePaths: [String] = [], imageData: Data? = nil,
             date: Date = Date(), isPinned: Bool = false) {
            self.id = id
            self.kind = kind
            self.text = text
            self.filePaths = filePaths
            self.imageData = imageData
            self.date = date
            self.isPinned = isPinned
        }

        var byteCount: Int {
            let textBytes = text?.lengthOfBytes(using: .utf8) ?? 0
            let pathBytes = filePaths.reduce(0) { $0 + $1.lengthOfBytes(using: .utf8) }
            return textBytes + pathBytes + (imageData?.count ?? 0)
        }

        func hasSameContent(as other: Entry) -> Bool {
            kind == other.kind && text == other.text &&
                filePaths == other.filePaths && imageData == other.imageData
        }
    }

    @Published private(set) var entries: [Entry] = []
    @Published private(set) var capacity: Int
    private(set) var running = false

    private let defaults: UserDefaults
    private let historyURL: URL
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let maxEntryBytes = 16 * 1024 * 1024
    private let maxTotalBytes = 64 * 1024 * 1024
    private let capacityRange = 10...500
    private static let capacityKey = "SMClipboardHistoryCapacity"
    private let ignoredPasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
    ]

    init(defaults: UserDefaults = .standard, historyURL: URL? = nil) {
        self.defaults = defaults
        self.historyURL = historyURL ?? Self.defaultHistoryURL
        let stored = defaults.object(forKey: Self.capacityKey) as? Int ?? 50
        capacity = min(capacityRange.upperBound, max(capacityRange.lowerBound, stored))
        entries = loadPersistedEntries()
        sortEntries()
        trimToLimits()
    }

    var pinnedCount: Int { entries.lazy.filter(\.isPinned).count }
    var unpinnedCount: Int { entries.count - pinnedCount }

    func start() {
        guard !running else { return }
        running = true
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        running = false
    }

    func updateCapacity(_ requested: Int) {
        let next = min(capacityRange.upperBound, max(capacityRange.lowerBound, requested))
        guard next != capacity else { return }
        capacity = next
        defaults.set(next, forKey: Self.capacityKey)
        trimToLimits()
        persistEntries()
    }

    private func poll() {
        let count = NSPasteboard.general.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        let pasteboard = NSPasteboard.general
        let currentTypes = Set((pasteboard.types ?? []).map(\.rawValue))
        guard ignoredPasteboardTypes.isDisjoint(with: currentTypes) else { return }

        if let paths = filePaths(from: pasteboard), !paths.isEmpty {
            record(Entry(kind: .file, filePaths: paths))
        } else if let image = NSImage(pasteboard: pasteboard),
                  let data = image.tiffRepresentation,
                  data.count <= maxEntryBytes {
            record(Entry(kind: .image, imageData: data))
        } else if let urlText = pasteboard.string(forType: .URL),
                  let entry = textEntry(urlText) {
            record(entry)
        } else if let text = pasteboard.string(forType: .string),
                  let entry = textEntry(text) {
            record(entry)
        }
    }

    private func textEntry(_ text: String) -> Entry? {
        guard !text.isEmpty, text.lengthOfBytes(using: .utf8) <= maxEntryBytes else { return nil }

        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if let paths = existingFilePaths(in: trimmed), !paths.isEmpty {
            return Entry(kind: .file, filePaths: paths)
        }
        if let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           scheme == "http" || scheme == "https" {
            return Entry(kind: .url, text: text)
        }
        return Entry(kind: .text, text: text)
    }

    private func filePaths(from pasteboard: NSPasteboard) -> [String]? {
        let objects = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) ?? []
        let paths = objects.compactMap { object -> String? in
            guard let url = object as? URL, url.isFileURL else { return nil }
            return url.standardizedFileURL.path
        }
        return paths.isEmpty ? nil : paths
    }

    private func existingFilePaths(in text: String) -> [String]? {
        let lines = text.split(whereSeparator: \Character.isNewline).map(String.init)
        guard !lines.isEmpty else { return nil }

        let paths = lines.compactMap { line -> String? in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            let path: String
            if let url = URL(string: trimmed), url.isFileURL {
                path = url.standardizedFileURL.path
            } else {
                path = (trimmed as NSString).expandingTildeInPath
            }
            return FileManager.default.fileExists(atPath: path) ? path : nil
        }
        return paths.count == lines.count ? paths : nil
    }

    /// 统一入口：去重、保留置顶状态，再执行容量与内存限制。
    func record(_ candidate: Entry) {
        let existing = entries.first { $0.hasSameContent(as: candidate) }
        entries.removeAll { $0.hasSameContent(as: candidate) }
        entries.append(Entry(id: existing?.id ?? candidate.id,
                             kind: candidate.kind,
                             text: candidate.text,
                             filePaths: candidate.filePaths,
                             imageData: candidate.imageData,
                             date: candidate.date,
                             isPinned: existing?.isPinned ?? false))
        sortEntries()
        trimToLimits()
        persistEntries()
    }

    private func sortEntries() {
        entries.sort {
            if $0.isPinned != $1.isPinned { return $0.isPinned && !$1.isPinned }
            return $0.date > $1.date
        }
    }

    private func trimToLimits() {
        while unpinnedCount > capacity {
            guard let index = entries.lastIndex(where: { !$0.isPinned }) else { break }
            entries.remove(at: index)
        }

        var totalBytes = entries.reduce(0) { $0 + $1.byteCount }
        while totalBytes > maxTotalBytes {
            guard let index = entries.lastIndex(where: { !$0.isPinned }) else { break }
            totalBytes -= entries[index].byteCount
            entries.remove(at: index)
        }
    }

    func togglePinned(_ id: UUID) {
        guard let index = entries.firstIndex(where: { $0.id == id }) else { return }
        var updated = entries[index]
        updated.isPinned.toggle()
        entries[index] = updated
        sortEntries()
        trimToLimits()
        persistEntries()
    }

    func remove(_ id: UUID) {
        entries.removeAll { $0.id == id }
        persistEntries()
    }

    func clearUnpinned() {
        entries.removeAll { !$0.isPinned }
        persistEntries()
    }

    func clear() {
        entries.removeAll()
        persistEntries()
    }

    /// 把历史条目按原始类型写回剪贴板。
    func copyToPasteboard(_ entry: Entry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch entry.kind {
        case .text:
            pasteboard.setString(entry.text ?? "", forType: .string)
        case .url:
            let text = entry.text ?? ""
            pasteboard.setString(text, forType: .string)
            pasteboard.setString(text, forType: .URL)
        case .file:
            pasteboard.writeObjects(entry.filePaths.map { NSURL(fileURLWithPath: $0) })
        case .image:
            if let data = entry.imageData {
                pasteboard.setData(data, forType: .tiff)
            }
        }
        // 写回历史不应再次被轮询器当作一条新记录。
        lastChangeCount = pasteboard.changeCount
    }

    private static var defaultHistoryURL: URL {
        let root = FileManager.default.urls(for: .applicationSupportDirectory,
                                            in: .userDomainMask).first!
        return root
            .appendingPathComponent("ForgeSweep", isDirectory: true)
            .appendingPathComponent("clipboard-history.plist")
    }

    private func loadPersistedEntries() -> [Entry] {
        guard let data = try? Data(contentsOf: historyURL),
              let decoded = try? PropertyListDecoder().decode([Entry].self, from: data) else {
            return []
        }
        return decoded
    }

    private func persistEntries() {
        do {
            let directory = historyURL.deletingLastPathComponent()
            try FileManager.default.createDirectory(at: directory,
                                                    withIntermediateDirectories: true,
                                                    attributes: [.posixPermissions: 0o700])
            try FileManager.default.setAttributes([.posixPermissions: 0o700],
                                                  ofItemAtPath: directory.path)
            let encoder = PropertyListEncoder()
            encoder.outputFormat = .binary
            let data = try encoder.encode(entries)
            try data.write(to: historyURL, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600],
                                                  ofItemAtPath: historyURL.path)
        } catch {
            // 历史记录失败不应影响剪贴板监听；下次变更会再次尝试写入。
        }
    }
}
